### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by siulynot** [breadwallet/breadwallet-android#20]
```
* What went wrong:
Execution failed for task ':app:compileCoreArm64-v8aDebugSharedLibraryCoreArm64-v8aDebugSharedLibraryMainC'.
> A build operation failed.
      C compiler failed while compiling wallet.c.
  See the complete log at: file:///home/administrator/breadwallet-android/app/build/tmp/compileCoreArm64-v8aDebugSharedLibraryCoreArm64-v8aDebugSharedLibraryMainC/output.txt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED


```
**Im trying to build android wallet in android studio. Already have ndk, cmake, and also updated modules. Still get the same errors.** 

Output.txt text:

```
compiling wallet.c failed.

In file included from /home/administrator/breadwallet-android/app/src/main/jni/transition/wallet.c:25:

In file included from /home/administrator/breadwallet-android/app/src/main/jni/transition/wallet.h:26:

In file included from /home/administrator/breadwallet-android/app/src/main/jni/breadwallet-core/BRWallet.h:29:

In file included from /home/administrator/breadwallet-android/app/src/main/jni/breadwallet-core/BRAddress.h:28:

/home/administrator/breadwallet-android/app/src/main/jni/breadwallet-core/BRCrypto.h:95:63: warning: implicitly declaring library function 'memset' with type 'void *(void *, int, unsigned long)' [-Wimplicit-function-declaration]

    void *(*volatile const memset_ptr)(void *, int, size_t) = memset;

                                                              ^

/home/administrator/breadwallet-android/app/src/main/jni/breadwallet-core/BRCrypto.h:95:63: note: include the header <string.h> or explicitly provide a declaration for 'memset'

In file included from /home/administrator/breadwallet-android/app/src/main/jni/transition/wallet.c:25:

/home/administrator/breadwallet-android/app/src/main/jni/transition/wallet.h:206:30: warning: no newline at end of file [-Wnewline-eof]

#endif //BREADWALLET_WALLET_H

                             ^

/home/administrator/breadwallet-android/app/src/main/jni/transition/wallet.c:648:62: error: too few arguments to function call, expected 5, have 4

    BRWalletSignTransaction(_wallet, tmpTx, key.u8, seedSize );

    ~~~~~~~~~~~~~~~~~~~~~~~                                  ^

/home/administrator/breadwallet-android/app/src/main/jni/breadwallet-core/BRWallet.h:139:1: note: 'BRWalletSignTransaction' declared here

int BRWalletSignTransaction(BRWallet *wallet, BRTransaction *tx, int forkId, const void *seed, size_t seedLen);

^

/home/administrator/breadwallet-android/app/src/main/jni/transition/wallet.c:809:37: error: too few arguments to function call, expected 4, have 3

    BRTransactionSign(tmpTx, &key, 1);

    ~~~~~~~~~~~~~~~~~               ^

/home/administrator/breadwallet-android/app/src/main/jni/breadwallet-core/BRTransaction.h:130:1: note: 'BRTransactionSign' declared here

int BRTransactionSign(BRTransaction *tx, int forkId, BRKey keys[], size_t keysCount);
```

**Comment by Gutyn** [comment]
the last two errors are due to the update in the core library, I have pushed a fix for it, please try again and let me know if you see any other errors.

**Comment by siulynot** [comment]
Thanks, so now i get new errors when building.

Information:Gradle tasks [clean, :app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :app:compileDebugSources, :app:compileDebugAndroidTestSources, :app:compileDebugUnitTestSources]
/home/administrator/breadwallet-android/app/src/main/jni/transition/PeerManager.c
Error:(282, 78) error: too many arguments to function call, expected 9, have 10
/home/administrator/breadwallet-android/app/src/main/jni/breadwallet-core/BRPeerManager.h
Information:(58, 1) 'BRPeerManagerSetCallbacks' declared here
/home/administrator/breadwallet-android/app/src/main/jni/breadwallet-core/BRCrypto.h
Warning:(95, 63) warning: implicitly declaring library function 'memset' with type 'void *(void *, int, unsigned long)' [-Wimplicit-function-declaration]
Information:(95, 63) include the header <string.h> or explicitly provide a declaration for 'memset'
In file included from /home/administrator/breadwallet-android/app/src/main/jni/transition/PeerManager.c:32:
/home/administrator/breadwallet-android/app/src/main/jni/transition/wallet.h:216:30: warning: no newline at end of file [-Wnewline-eof]
Warning:(95, 63) warning: implicitly declaring library function 'memset' with type 'void *(void *, int, unsigned long)' [-Wimplicit-function-declaration]
Information:(95, 63) include the header <string.h> or explicitly provide a declaration for 'memset'
In file included from /home/administrator/breadwallet-android/app/src/main/jni/transition/wallet.c:25:
/home/administrator/breadwallet-android/app/src/main/jni/transition/wallet.h:216:30: warning: no newline at end of file [-Wnewline-eof]
/home/administrator/breadwallet-android/app/src/main/jni/transition/wallet.c
Warning:(815, 12) warning: unused variable 'len' [-Wunused-variable]
Error:(957, 34) error: use of undeclared identifier 'tmpTx'
Error:Execution failed for task ':app:compileCoreArm64-v8aDebugSharedLibraryCoreArm64-v8aDebugSharedLibraryMainC'.
> Multiple build operations failed.
      C compiler failed while compiling PeerManager.c.
      C compiler failed while compiling wallet.c.
  See the complete log at: file:///home/administrator/breadwallet-android/app/build/tmp/compileCoreArm64-v8aDebugSharedLibraryCoreArm64-v8aDebugSharedLibraryMainC/output.txt
Information:BUILD FAILED
Information:Total time: 20.96 secs
Information:3 errors
Information:3 warnings
Information:See complete output in console

**Comment by siulynot** [comment]
also this printed in the console:

:app:compileCoreArm64-v8aDebugSharedLibraryCoreArm64-v8aDebugSharedLibraryMainC
In file included from /home/administrator/breadwallet-android/app/src/main/jni/transition/PeerManager.c:25:
In file included from /home/administrator/breadwallet-android/app/src/main/jni/transition/PeerManager.h:27:
In file included from /home/administrator/breadwallet-android/app/src/main/jni/breadwallet-core/BRPeerManager.h:28:
In file included from /home/administrator/breadwallet-android/app/src/main/jni/breadwallet-core/BRPeer.h:30:
In file included from /home/administrator/breadwallet-android/app/src/main/jni/breadwallet-core/BRAddress.h:28:
/home/administrator/breadwallet-android/app/src/main/jni/breadwallet-core/BRCrypto.h:95:63: warning: implicitly declaring library function 'memset' with type 'void *(void *, int, unsigned long)' [-Wimplicit-function-declaration]
    void *(*volatile const memset_ptr)(void *, int, size_t) = memset;
                                                              ^
/home/administrator/breadwallet-android/app/src/main/jni/breadwallet-core/BRCrypto.h:95:63: note: include the header <string.h> or explicitly provide a declaration for 'memset'
In file included from /home/administrator/breadwallet-android/app/src/main/jni/transition/PeerManager.c:32:
/home/administrator/breadwallet-android/app/src/main/jni/transition/wallet.h:216:30: warning: no newline at end of file [-Wnewline-eof]
#endif //BREADWALLET_WALLET_H
                             ^
/home/administrator/breadwallet-android/app/src/main/jni/transition/PeerManager.c:282:78: error: too many arguments to function call, expected 9, have 10
                                  saveBlocks, savePeers, networkIsReachable, threadCleanup);
                                                                             ^~~~~~~~~~~~~
/home/administrator/breadwallet-android/app/src/main/jni/breadwallet-core/BRPeerManager.h:58:1: note: 'BRPeerManagerSetCallbacks' declared here
void BRPeerManagerSetCallbacks(BRPeerManager *manager, void *info,
^
2 warnings and 1 error generated.

In file included from /home/administrator/breadwallet-android/app/src/main/jni/transition/wallet.c:25:
In file included from /home/administrator/breadwallet-android/app/src/main/jni/transition/wallet.h:26:
In file included from /home/administrator/breadwallet-android/app/src/main/jni/breadwallet-core/BRWallet.h:29:
In file included from /home/administrator/breadwallet-android/app/src/main/jni/breadwallet-core/BRAddress.h:28:
/home/administrator/breadwallet-android/app/src/main/jni/breadwallet-core/BRCrypto.h:95:63: warning: implicitly declaring library function 'memset' with type 'void *(void *, int, unsigned long)' [-Wimplicit-function-declaration]
    void *(*volatile const memset_ptr)(void *, int, size_t) = memset;
                                                              ^
/home/administrator/breadwallet-android/app/src/main/jni/breadwallet-core/BRCrypto.h:95:63: note: include the header <string.h> or explicitly provide a declaration for 'memset'
In file included from /home/administrator/breadwallet-android/app/src/main/jni/transition/wallet.c:25:
/home/administrator/breadwallet-android/app/src/main/jni/transition/wallet.h:216:30: warning: no newline at end of file [-Wnewline-eof]
#endif //BREADWALLET_WALLET_H
                             ^
/home/administrator/breadwallet-android/app/src/main/jni/transition/wallet.c:815:12: warning: unused variable 'len' [-Wunused-variable]
    size_t len = BRTransactionSerialize(tmpTx, buf, sizeof(buf));
           ^
/home/administrator/breadwallet-android/app/src/main/jni/transition/wallet.c:957:34: error: use of undeclared identifier 'tmpTx'
    assert(BRTransactionIsSigned(tmpTx));
                                 ^
3 warnings and 1 error generated.


 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileCoreArm64-v8aDebugSharedLibraryCoreArm64-v8aDebugSharedLibraryMainC'.
> Multiple build operations failed.
      C compiler failed while compiling PeerManager.c.
      C compiler failed while compiling wallet.c.
  See the complete log at: file:///home/administrator/breadwallet-android/app/build/tmp/compileCoreArm64-v8aDebugSharedLibraryCoreArm64-v8aDebugSharedLibraryMainC/output.txt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 20.96 secs

**Comment by Gutyn** [comment]
I believe the errors are fixed now, please try to pull and rebuild.

**Comment by siulynot** [comment]
thanks!

**Comment by siulynot** [comment]
ill let you know if it works

**Comment by siulynot** [comment]
Im still having issues :/

:app:compileDebugAndroidTestJavaWithJavac
/home/administrator/breadwallet-android/app/src/androidTest/java/com/breadwallet/security/KeyStoreTests.java:57: error: exception BRKeystoreErrorException is never thrown in body of corresponding try statement
        } catch (BRKeystoreErrorException e) {
          ^
/home/administrator/breadwallet-android/app/src/androidTest/java/com/breadwallet/security/KeyStoreTests.java:66: error: exception BRKeystoreErrorException is never thrown in body of corresponding try statement
        } catch (BRKeystoreErrorException e) {
          ^
/home/administrator/breadwallet-android/app/src/androidTest/java/com/breadwallet/security/KeyStoreTests.java:75: error: exception BRKeystoreErrorException is never thrown in body of corresponding try statement
        } catch (BRKeystoreErrorException e) {
          ^
/home/administrator/breadwallet-android/app/src/androidTest/java/com/breadwallet/security/KeyStoreTests.java:83: error: exception BRKeystoreErrorException is never thrown in body of corresponding try statement
        } catch (BRKeystoreErrorException e) {
          ^
/home/administrator/breadwallet-android/app/src/androidTest/java/com/breadwallet/security/KeyStoreTests.java:56: error: unreported exception UserNotAuthenticatedException; must be caught or declared to be thrown
            KeyStoreManager.putPhrase(phrase, mActivityRule.getActivity(), 0);
                                     ^
/home/administrator/breadwallet-android/app/src/androidTest/java/com/breadwallet/security/KeyStoreTests.java:65: error: unreported exception UserNotAuthenticatedException; must be caught or declared to be thrown
            freshGet = KeyStoreManager.getPhrase(mActivityRule.getActivity(), 0);
                                                ^
/home/administrator/breadwallet-android/app/src/androidTest/java/com/breadwallet/security/KeyStoreTests.java:74: error: unreported exception UserNotAuthenticatedException; must be caught or declared to be thrown
            KeyStoreManager.putPhrase(japPhrase, mActivityRule.getActivity(), 0);
                                     ^
/home/administrator/breadwallet-android/app/src/androidTest/java/com/breadwallet/security/KeyStoreTests.java:82: error: unreported exception UserNotAuthenticatedException; must be caught or declared to be thrown
            freshJapGet = KeyStoreManager.getPhrase(mActivityRule.getActivity(), 0);
                                                   ^
/home/administrator/breadwallet-android/app/src/androidTest/java/com/breadwallet/security/KeyStoreTests.java:95: error: exception BRKeystoreErrorException is never thrown in body of corresponding try statement
        } catch (BRKeystoreErrorException e) {
          ^
/home/administrator/breadwallet-android/app/src/androidTest/java/com/breadwallet/security/KeyStoreTests.java:103: error: exception BRKeystoreErrorException is never thrown in body of corresponding try statement
        } catch (BRKeystoreErrorException e) {
          ^
/home/administrator/breadwallet-android/app/src/androidTest/java/com/breadwallet/security/KeyStoreTests.java:94: error: unreported exception UserNotAuthenticatedException; must be caught or declared to be thrown
            KeyStoreManager.putCanary(canary, mActivityRule.getActivity(), 0);
                                     ^
/home/administrator/breadwallet-android/app/src/androidTest/java/com/breadwallet/security/KeyStoreTests.java:102: error: unreported exception UserNotAuthenticatedException; must be caught or declared to be thrown
            freshGet = KeyStoreManager.getCanary(mActivityRule.getActivity(), 0);
                                                ^
/home/administrator/breadwallet-android/app/src/androidTest/java/com/breadwallet/security/KeyStoreTests.java:222: error: exception BRKeystoreErrorException is never thrown in body of corresponding try statement
        } catch (BRKeystoreErrorException e) {
          ^
/home/administrator/breadwallet-android/app/src/androidTest/java/com/breadwallet/security/KeyStoreTests.java:228: error: exception BRKeystoreErrorException is never thrown in body of corresponding try statement
        } catch (BRKeystoreErrorException e) {
          ^
/home/administrator/breadwallet-android/app/src/androidTest/java/com/breadwallet/security/KeyStoreTests.java:256: error: exception BRKeystoreErrorException is never thrown in body of corresponding try statement
        } catch (BRKeystoreErrorException e) {
          ^
/home/administrator/breadwallet-android/app/src/androidTest/java/com/breadwallet/security/KeyStoreTests.java:264: error: exception BRKeystoreErrorException is never thrown in body of corresponding try statement
        } catch (BRKeystoreErrorException e) {
          ^
/home/administrator/breadwallet-android/app/src/androidTest/java/com/breadwallet/security/KeyStoreTests.java:221: error: unreported exception UserNotAuthenticatedException; must be caught or declared to be thrown
            KeyStoreManager.putPhrase("axis husband project any sea patch drip tip spirit tide bring belt".getBytes(), mActivityRule.getActivity(), 0);
                                     ^
/home/administrator/breadwallet-android/app/src/androidTest/java/com/breadwallet/security/KeyStoreTests.java:227: error: unreported exception UserNotAuthenticatedException; must be caught or declared to be thrown
            KeyStoreManager.putCanary("canary", mActivityRule.getActivity(), 0);
                                     ^
/home/administrator/breadwallet-android/app/src/androidTest/java/com/breadwallet/security/KeyStoreTests.java:255: error: unreported exception UserNotAuthenticatedException; must be caught or declared to be thrown
            phrase = KeyStoreManager.getPhrase(mActivityRule.getActivity(), 0);
                                              ^
/home/administrator/breadwallet-android/app/src/androidTest/java/com/breadwallet/security/KeyStoreTests.java:263: error: unreported exception UserNotAuthenticatedException; must be caught or declared to be thrown
            canary = KeyStoreManager.getCanary(mActivityRule.getActivity(), 0);
                                              ^
20 errors

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugAndroidTestJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 36.712 secs

**Comment by Gutyn** [comment]
Apologize for that, the tests have not been updated, I just pushed an update, please try now.
